### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by xelmas** [RedFoxFinn/ChatList#1]
Sovelluksen kuvaus on huolellisesti laadittu ja toimintoja mietitty. Tässä versiossa mahdollista oli testata superuser rekisteröitymistä sekä sisäänkirjautumista. Salasanan vaihtoa testasin, mutta kaatui ilmoittaen "bad request". Koodi on tällä hetkellä selkeää, mutta sovelluksen laajentuessa harkitsisin, että jakaisi osia omiin moduuleihinsa. Esimerkiksi tunnusten luomisen ja autentikoinnin omaan users-moduuliin.

Tietokanta vaikuttaa järkevästi suunnitellulta. Moderators-taulu tosin ei vaikuta viittaavan nykyisellään mihinkään, siihen voisi lisätä viittauksen Admins tauluun admin_id. Sovellukseen voisi lisätä myös istunnot, jotta tieto säilyy (sessions) ja csrf-token tarkistukset.

**Comment by RedFoxFinn** [comment]
Oikein hyviä pointteja, pidän muistissa edistäessäni sovellusta.
