### ISSUE TITLE
Välipalautus 3 vertaisarviointi

### ISSUE THREAD

**Issue by anuvirtane** [RedFoxFinn/ChatList#2]
Moikka,

Ensin pääasiat: Sovellus toimii niiltä osin ja sillä tavalla kuin readmessa on luvattu. Koodia on paloiteltu osiin järkevästi, ja tietokannan rakenne on toimiva. Readme onajan tasalla, ja tietokannan taulut kuvailtu informatiivisesti. Sovelluksen ulkoasuun on myös jo kiinnitetty huomiota. Oikein hyvää työtä kokonaisuudessaan!

Sitten pienempiä huomioita ja parannusehdotuksia siinä järjestyksessä, mitä niitä tuli vastaan sovellusta kokeillessani:

**Kuvat Readmessa**
Readmessa on kuvia, mikä on oikein kiva sinänsä. Kuitenkin niiden näyttämisessä käytetty syntaksi ei toimi Githubissa eikä minulla lokaalisti. Kokeilin lokaalisti kahta toimivaa vaihtoehtoa, jotka alla toimimattoman esimerkin jälkeen:

Tämän asemesta:
`[Sovelluksen käyttöönottoruutu](https://github.com/RedFoxFinn/ChatList/tree/main/docs/init_required.png | width=300)`

Voit käyttää tätä:

`![Sovelluksen käyttöönottoruutu](/docs/init_required.png)`

Tai tätä:
`<img src="docs/init_required.png" width="300">`

**Yksi muutostoive**
Readme lupasi, että jos en aseta .env-tiedostoon muuttujaa CUSTOM_APP_NAME, sovelluksen nimeksi tulee ChatList. Jätin CUSTOM_APP_NAME -muuttujan asettamatta, ja sen seurauksena sovellus ei käynnistynyt, koska config_module.pyssä on rivillä 7:
    `"CUSTOM_APP_NAME") != None or len(getenv("CUSTOM_APP_NAME")) == 0 else "ChatList"`
Siinä varmaan pitäisi olla:
   `"CUSTOM_APP_NAME") == None or len(getenv("CUSTOM_APP_NAME")) == 0 else "ChatList"`
Tuolla muutoksella sovellus käynnistyi.

**Käytettävyyshuomio rekisteröityömisestä käyttäjäksi**
Ensimmäistä käyttäjää rekisteröidessä syötin pyydetyt tiedot, ja sain virheilmoituksen
“Virheellinen syöte yhdessä tai useammassa kentässä” ilman, että sain selville, mikä meni väärin. Koodia kaivelemalla arvelin, että salasanani ei täyttänyt vaatimuksia. Ilmoitus siitä, että kyse on siitä, että salasanan vaatimukset eivät täyty, tekisi sovelluksen käyttämisestä miellyttävämpää.

**Käytettävyyshuomio keskusteluryhmän lisäämisestä**
Sijainnissa /management/chats on mahdollista lisätä keskusteluryhmä. Syötin kenttiin tekstisyötteet ja valitsin valikosta ylläpitäjän. Tämä johti Internal server error -näkymään. Terminaalin virheviestin perusteella päättelin, että johonkin tekstikenttään olisi pitänyt syöttää numero. Syötteitä muuttamalla keskusteluryhmän lisääminen onnistui. Tässä olisi myös käyttäjälle miellyttävämpää, jos lomake kertoisi, minkälaisia syötteitä halutaan, tai väärän syötteen antaminen johtaisi virheviestiin, jossa kerrottaisiin, mikä meni väärin.

Yt,
Anu Virtanen

**Comment by RedFoxFinn** [comment]
Oikein hyviä ja aiheellisia huomioita. Otan ne heti seuraavaksi työn alle :)
